// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.210
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MadsKristensen.ImageOptimizer
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidImageOptimizerPkgString = "bf95754f-93d3-42ff-bfe3-e05d23188b08";
        public const string guidAutoloadImagesString = "ca4b4a68-7c99-489f-8245-8eb13f2ac2f8";
        public const string guidAutoloadFoldersString = "ca4b4a68-7c99-489f-8245-8eb13f2ac2f9";
        public const string guidImageOptimizerCmdSetString = "d3662d85-2693-4ff5-97aa-3878453c787b";
        public static Guid guidImageOptimizerPkg = new Guid(guidImageOptimizerPkgString);
        public static Guid guidAutoloadImages = new Guid(guidAutoloadImagesString);
        public static Guid guidAutoloadFolders = new Guid(guidAutoloadFoldersString);
        public static Guid guidImageOptimizerCmdSet = new Guid(guidImageOptimizerCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenu = 0x1010;
        public const int MyMenuGroup = 0x1020;
        public const int OptimizeGroup = 0x2000;
        public const int ClipboardGroup = 0x2100;
        public const int cmdOptimizelossy = 0x0100;
        public const int cmdOptimizelossless = 0x0150;
        public const int cmdCopyDataUri = 0x0200;
    }
}
