// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MadsKristensen.ImageOptimizer
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidImageOptimizerPkgString = "bf95754f-93d3-42ff-bfe3-e05d23188b08";
        public static Guid guidImageOptimizerPkg = new Guid(guidImageOptimizerPkgString);

        public const string guidAutoloadImagesString = "ca4b4a68-7c99-489f-8245-8eb13f2ac2f8";
        public static Guid guidAutoloadImages = new Guid(guidAutoloadImagesString);

        public const string guidAutoloadFoldersString = "ca4b4a68-7c99-489f-8245-8eb13f2ac2f9";
        public static Guid guidAutoloadFolders = new Guid(guidAutoloadFoldersString);

        public const string guidBitmapOnlyUiContextString = "a076dc84-3c1c-45c2-ae98-f5f1a43ab976";
        public static Guid guidBitmapOnlyUiContext = new Guid(guidBitmapOnlyUiContextString);

        public const string guidImageOptimizerCmdSetString = "d3662d85-2693-4ff5-97aa-3878453c787b";
        public static Guid guidImageOptimizerCmdSet = new Guid(guidImageOptimizerCmdSetString);

        public const string guidWorkspaceExplorerToolWindowPackageCmdSetString = "cfb400f1-5c60-4f3c-856e-180d28def0b7";
        public static Guid guidWorkspaceExplorerToolWindowPackageCmdSet = new Guid(guidWorkspaceExplorerToolWindowPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenu = 0x1010;
        public const int MyMenuGroup = 0x1020;
        public const int OptimizeGroup = 0x2000;
        public const int ClipboardGroup = 0x2100;
        public const int cmdOptimizelossy = 0x0100;
        public const int cmdOptimizelossless = 0x0150;
        public const int cmdCopyDataUri = 0x0200;
        public const int cmdResize = 0x0250;
        public const int WorkspaceContextMenuGroup = 0x0004;
        public const int WorkspaceContextMenu = 0x0005;
        public const int WorkspaceOptimizeGroup = 0x0006;
        public const int cmdWorkspaceOptimizelossless = 0x0007;
        public const int cmdWorkspaceOptimizelossy = 0x0008;
        public const int cmdWorkspaceResize = 0x0009;
        public const int idmWSE_ContextMenu = 0x0002;
        public const int idgWSE_ContextMenu_BuildDebugActions = 0x0014;
        public const int idgWSE_ContextMenu_FileContextActions = 0x0017;
        public const int idgAddNew_FilesFolders = 0x2201;
        public const int idgWSE_ContextMenu_ScopeActions = 0x0016;
    }
}