// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MadsKristensen.ImageOptimizer
{
    static class Vsix
    {
        public const string Id = "bf95754f-93d3-42ff-bfe3-e05d23188b08";
        public const string Name = "Image Optimizer";
        public const string Description = @"Uses industry standard tools to optimize any JPEG, PNG and Gifs - including animated Gifs. Can do both lossy and lossless optimization.";
        public const string Language = "en-US";
        public const string Version = "4.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "image, png, gif, jpg, jpeg, compression, optimization, zopfli";
    }
}
