// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MadsKristensen.ImageOptimizer
{
    internal sealed partial class Vsix
    {
        public const string Id = "fc4e241f-57de-4032-9c89-527984c0a0ae";
        public const string Name = "Image Optimizer (64-bit)";
        public const string Description = @"Uses industry standard tools to optimize any JPEG, PNG and Gifs - including animated Gifs. Can do both lossy and lossless optimization.";
        public const string Language = "en-US";
        public const string Version = "5.0.999";
        public const string Author = "Mads Kristensen";
        public const string Tags = "image, png, gif, jpg, jpeg, compression, optimization, zopfli";
    }
}
